wait("0.2")
local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("TheGoatPro's Scripts!", "Midnight")
local Tab = Window:NewTab("All TheGoatPros Scripts")
local Section = Tab:NewSection("Iat Scripts!")
Section:NewButton("thunder hub", "this is goated iat script", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AllFilmOffical/MainHub/main/Allfilm"))()
    print("Clicked")
end)
Section:NewButton("goats hub", "my script yay", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AllFilmOffical/goathub/main/Main/script", true))()
    print("Clicked")
end)
Section:NewButton("faded da hood", "currently goat da hood script", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/NighterEpic/Faded/main/YesEpic", true))()
end)
Section:NewButton("GOATED FUNKY FRIDAY", "currently goat FUNKY FRIDAY script", function()
loadstring(game:HttpGet("https://scriptblox.com/raw/XMAS-Event-or-Funky-Friday-Auto-Player-Mobile-6721"))()
end)
Section:NewButton("the strongest battlegrounds", "goated saitama battlegrounds script", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/KirbleSensei/stuff/main/The%20Strongest%20Battlegrounds%20GUI"))()
end)
Section:NewButton("Furk Yba Script (goated pc and mobile)", "idk bout u buddy but those aut creators are definitely not any better then yba", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/UltraStuff/scripts2/main/yba", true))()
end)

Tab:NewSection("OWNER = THEGOATPRO")
local Section = Tab:NewSection(" CO OWNER = ALLFILM")
local Section = Tab:NewSection("OWNER OF HUB = THEGOATPRO")
